import 'knowledge_entry.dart';

/// Authoritative knowledge entries for all 24 canonical BMC Administrative Wards.
/// Sourced from `supabase/functions/_shared/departments.ts`.
final List<KnowledgeEntry> wardsKnowledgeEntries = [
  const KnowledgeEntry(
    id: 'wards_overview',
    title: '24 Canonical BMC Administrative Wards',
    topic: 'wards',
    audience: 'all',
    tags: [
      'wards',
      'bmc wards',
      '24 wards',
      'ward list',
      'mumbai administrative wards',
    ],
    canonicalContent:
        'Greater Mumbai is divided into 24 administrative Wards across 3 regions:\n'
        '• Island City: A (Colaba, Fort), B (Sandhurst Rd), C (Marine Lines), D (Grant Rd, Malabar Hill), E (Byculla), F/North (Matunga, Sion), F/South (Parel), G/North (Dadar, Dharavi), G/South (Worli, Lower Parel).\n'
        '• Western Suburbs: H/East (Bandra E, Santacruz E), H/West (Bandra W, Khar), K/East (Andheri E), K/West (Andheri W), P/North (Malad), P/South (Goregaon), R/Central (Borivali), R/North (Dahisar), R/South (Kandivali).\n'
        '• Eastern Suburbs: L (Kurla), M/East (Govandi, Mankhurd), M/West (Chembur), N (Ghatkopar), S (Bhandup, Powai), T (Mulund).\n'
        'Every grievance reported in CivicFix is automatically geotagged and scoped to its specific Ward for local engineering dispatch.',
    relatedTopics: [
      'departments_overview',
      'assignment_workflow',
    ],
    sourceReference: 'supabase/functions/_shared/departments.ts - CANONICAL_WARDS',
  ),
  const KnowledgeEntry(
    id: 'ward_a',
    title: 'Ward A (Colaba, Fort, Nariman Point)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward a', 'colaba', 'fort', 'nariman point', 'cuffe parade', 'churchgate'],
    canonicalContent: 'Ward A covers South Mumbai areas including Colaba, Churchgate, Fort, Nariman Point, and Cuffe Parade.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_b',
    title: 'Ward B (Sandhurst Road, Dongri, Masjid Bunder)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward b', 'sandhurst road', 'dongri', 'masjid bunder'],
    canonicalContent: 'Ward B covers Sandhurst Road, Dongri, Masjid Bunder, and surrounding markets.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_c',
    title: 'Ward C (Marine Lines, Bhuleshwar, Kalbadevi)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward c', 'marine lines', 'bhuleshwar', 'kalbadevi'],
    canonicalContent: 'Ward C covers Marine Lines, Bhuleshwar, Kalbadevi, and Chira Bazaar.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_d',
    title: 'Ward D (Grant Road, Malabar Hill, Tardeo)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward d', 'grant road', 'malabar hill', 'tardeo', 'walkeshwar', 'breach candy'],
    canonicalContent: 'Ward D covers Malabar Hill, Walkeshwar, Breach Candy, Tardeo, and Grant Road.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_e',
    title: 'Ward E (Byculla, Mumbai Central, Mazgaon)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward e', 'byculla', 'mumbai central', 'mazgaon', 'nagpada'],
    canonicalContent: 'Ward E covers Byculla, Mumbai Central, Mazgaon, Nagpada, and Agripada.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_f_north',
    title: 'Ward F/North (Matunga, Sion, Wadala)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward f/north', 'ward f north', 'matunga', 'sion', 'wadala'],
    canonicalContent: 'Ward F/North covers Matunga, Sion, Wadala East, and GTB Nagar.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_f_south',
    title: 'Ward F/South (Parel, Sewri, Naigaon)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward f/south', 'ward f south', 'parel', 'sewri', 'naigaon'],
    canonicalContent: 'Ward F/South covers Parel, Sewri, Naigaon, and Lalbaug.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_g_north',
    title: 'Ward G/North (Dharavi, Dadar West, Mahim)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward g/north', 'ward g north', 'dharavi', 'dadar', 'mahim'],
    canonicalContent: 'Ward G/North covers Dharavi, Dadar West, Mahim, and Shivaji Park.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_g_south',
    title: 'Ward G/South (Worli, Lower Parel, Prabhadevi)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward g/south', 'ward g south', 'worli', 'lower parel', 'prabhadevi'],
    canonicalContent: 'Ward G/South covers Worli, Lower Parel, Prabhadevi, and Mahalaxmi.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_h_east',
    title: 'Ward H/East (Bandra East, Santacruz East, Kalina)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward h/east', 'ward h east', 'bandra east', 'santacruz east', 'kalina', 'bkc'],
    canonicalContent: 'Ward H/East covers Bandra East, Santacruz East, Kalina, and the Bandra Kurla Complex (BKC).',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_h_west',
    title: 'Ward H/West (Bandra West, Khar West, Santacruz West)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward h/west', 'ward h west', 'bandra west', 'khar west', 'santacruz west'],
    canonicalContent: 'Ward H/West covers Bandra West, Khar West, and Santacruz West.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_k_east',
    title: 'Ward K/East (Andheri East, Jogeshwari East, Vile Parle East)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward k/east', 'ward k east', 'andheri east', 'jogeshwari east', 'vile parle east'],
    canonicalContent: 'Ward K/East covers Andheri East, Jogeshwari East, Vile Parle East, MIDC, and SEEPZ.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_k_west',
    title: 'Ward K/West (Andheri West, Jogeshwari West, Vile Parle West)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward k/west', 'ward k west', 'andheri west', 'jogeshwari west', 'vile parle west', 'lokhandwala'],
    canonicalContent: 'Ward K/West covers Andheri West, Lokhandwala, Versova, Jogeshwari West, and Juhu.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_l',
    title: 'Ward L (Kurla, Sakinaka, Chandivali)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward l', 'kurla', 'sakinaka', 'chandivali'],
    canonicalContent: 'Ward L covers Kurla West/East, Sakinaka, Chandivali, and Asalpha.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_m_east',
    title: 'Ward M/East (Govandi, Mankhurd, Shivaji Nagar)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward m/east', 'ward m east', 'govandi', 'mankhurd', 'shivaji nagar', 'deonar'],
    canonicalContent: 'Ward M/East covers Govandi, Mankhurd, Shivaji Nagar, and Deonar.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_m_west',
    title: 'Ward M/West (Chembur, Tilak Nagar, Mahul)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward m/west', 'ward m west', 'chembur', 'tilak nagar', 'mahul'],
    canonicalContent: 'Ward M/West covers Chembur, Tilak Nagar, Pestom Sagar, and Mahul.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_n',
    title: 'Ward N (Ghatkopar, Vikhroli West)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward n', 'ghatkopar', 'vikhroli west', 'pant nagar'],
    canonicalContent: 'Ward N covers Ghatkopar East/West, Pant Nagar, and Vikhroli West.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_p_north',
    title: 'Ward P/North (Malad, Marve, Aksa)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward p/north', 'ward p north', 'malad', 'marve', 'aksa', 'manori'],
    canonicalContent: 'Ward P/North covers Malad East/West, Marve, Aksa, and Madh Island.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_p_south',
    title: 'Ward P/South (Goregaon)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward p/south', 'ward p south', 'goregaon', 'aarey', 'oshiwara'],
    canonicalContent: 'Ward P/South covers Goregaon East/West, Aarey Colony, and Bangur Nagar.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_r_central',
    title: 'Ward R/Central (Borivali)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward r/central', 'ward r central', 'borivali', 'gorai', 'shimpoli'],
    canonicalContent: 'Ward R/Central covers Borivali East/West, Gorai, and Shimpoli.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_r_north',
    title: 'Ward R/North (Dahisar)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward r/north', 'ward r north', 'dahisar', 'rawalpada'],
    canonicalContent: 'Ward R/North covers Dahisar East/West and northern municipal boundary limits.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_r_south',
    title: 'Ward R/South (Kandivali)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward r/south', 'ward r south', 'kandivali', 'charkop', 'lokhandwala kandivali'],
    canonicalContent: 'Ward R/South covers Kandivali East/West, Charkop, and Mahavir Nagar.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_s',
    title: 'Ward S (Bhandup, Powai, Kanjurmarg)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward s', 'bhandup', 'powai', 'kanjurmarg', 'vikhroli east'],
    canonicalContent: 'Ward S covers Bhandup West/East, Powai, Kanjurmarg, and Vikhroli East.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
  const KnowledgeEntry(
    id: 'ward_t',
    title: 'Ward T (Mulund, Nahur)',
    topic: 'wards',
    audience: 'all',
    tags: ['ward t', 'mulund', 'nahur'],
    canonicalContent: 'Ward T covers Mulund East/West and Nahur.',
    relatedTopics: ['wards_overview'],
    sourceReference: 'supabase/functions/_shared/departments.ts',
  ),
];
