// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl9MwMgp0tr9gg9qI3uAq3lX-UNkQjt58',
    appId: '1:594524642298:web:2acb5c969feb9b29586243',
    messagingSenderId: '594524642298',
    projectId: 'civicfix-38d53',
    authDomain: 'civicfix-38d53.firebaseapp.com',
    storageBucket: 'civicfix-38d53.firebasestorage.app',
    measurementId: 'G-700QBXK6VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF91IjkZROyID70xd0Ug-VE7TI_rLHEaU',
    appId: '1:594524642298:android:59ef631696fb5534586243',
    messagingSenderId: '594524642298',
    projectId: 'civicfix-38d53',
    storageBucket: 'civicfix-38d53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXt2jvefefxUxn6xYYLr96OBCotyvHUpY',
    appId: '1:594524642298:ios:1254a29ae5f3aecf586243',
    messagingSenderId: '594524642298',
    projectId: 'civicfix-38d53',
    storageBucket: 'civicfix-38d53.firebasestorage.app',
    iosBundleId: 'com.example.civicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXt2jvefefxUxn6xYYLr96OBCotyvHUpY',
    appId: '1:594524642298:ios:1254a29ae5f3aecf586243',
    messagingSenderId: '594524642298',
    projectId: 'civicfix-38d53',
    storageBucket: 'civicfix-38d53.firebasestorage.app',
    iosBundleId: 'com.example.civicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl9MwMgp0tr9gg9qI3uAq3lX-UNkQjt58',
    appId: '1:594524642298:web:42e6565ee7810e13586243',
    messagingSenderId: '594524642298',
    projectId: 'civicfix-38d53',
    authDomain: 'civicfix-38d53.firebaseapp.com',
    storageBucket: 'civicfix-38d53.firebasestorage.app',
    measurementId: 'G-22X08QB8V4',
  );
}
